---
- name: "Install Maven"
  hosts: localhost
  gather_facts: false
  check_mode: false
  become: yes
  become_method: sudo
  tasks:
    - name: "Create Maven group"
      ansible.builtin.group:
        name: maven
        state: present

    - name: "Create Maven User"
      ansible.builtin.user:
        name: maven
        state: present

    - name: "Install OpenJDK"
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: "Find Java home"
      shell: readlink -f /usr/bin/java | sed "s:/bin/java::"
      register: java_home_output
      changed_when: false

    - name: "Set JAVA_HOME environment variable in /etc/environment"
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: '^JAVA_HOME='
        line: 'JAVA_HOME={{ java_home_output.stdout }}'

    - name: "Create Maven Directory"
      ansible.builtin.file:
        path: /opt/maven
        owner: maven
        mode: 0755
        recurse: yes
        state: directory

    - name: "Download and unarchive maven"
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
        dest: /opt/maven
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: "Change The Ownership Of maven Directory"
      ansible.builtin.file:
        path: /opt/maven
        owner: maven
        group: maven
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: "Alternatives Maven link created"
      community.general.alternatives:
        name: maven
        link: /usr/bin/mvn
        path: /opt/maven/bin/mvn
        priority: 1001

    - name: "Check Maven Version"
      shell: mvn -version
      environment:
        JAVA_HOME: "{{ java_home_output.stdout }}"