apiVersion: apps/v1
kind: Deployment
metadata:
  name: joshua-tasksmanager-app
  labels:
    app: joshua-tasksmanager-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: joshua-tasksmanager-app
  template:
    metadata:
      labels:
        app: joshua-tasksmanager-app
    spec:
      containers:
        - name: joshua-tasksmanager-app
          image: joshuamoochooram/tasksmanager:latest
          ports:
            - containerPort: 8082