apiVersion: v1
kind: Service
metadata:
  name: joshua-tasksmanager-app-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8082
      targetPort: 8089
      protocol: TCP
  selector:
    app: joshua-tasksmanager-app